import 'package:cloud_firestore/cloud_firestore.dart';

enum KnittingEventType {
  needlePurchase,   // 바늘 구입
  yarnPurchase,     // 실 구입
  patternPurchase,  // 도안 구입
  toolPurchase,     // 기타 도구 구입
  swatchComplete,   // 스와치 완료
  projectStart,     // 프로젝트 시작
  projectComplete,  // 프로젝트 완료
  knitAlongStart,   // 함뜨(함께뜨기) 시작
  memo,             // 메모
}

extension KnittingEventTypeX on KnittingEventType {
  String get value => name;

  String label(bool isKorean) {
    if (isKorean) {
      switch (this) {
        case KnittingEventType.needlePurchase: return '바늘 구입';
        case KnittingEventType.yarnPurchase: return '실 구입';
        case KnittingEventType.patternPurchase: return '도안 구입';
        case KnittingEventType.toolPurchase: return '도구 구입';
        case KnittingEventType.swatchComplete: return '스와치 완료';
        case KnittingEventType.projectStart: return '프로젝트 시작';
        case KnittingEventType.projectComplete: return '프로젝트 완료';
        case KnittingEventType.knitAlongStart: return '함뜨 시작';
        case KnittingEventType.memo: return '메모';
      }
    } else {
      switch (this) {
        case KnittingEventType.needlePurchase: return 'Needle Purchase';
        case KnittingEventType.yarnPurchase: return 'Yarn Purchase';
        case KnittingEventType.patternPurchase: return 'Pattern Purchase';
        case KnittingEventType.toolPurchase: return 'Tool Purchase';
        case KnittingEventType.swatchComplete: return 'Swatch Done';
        case KnittingEventType.projectStart: return 'Project Start';
        case KnittingEventType.projectComplete: return 'Project Complete';
        case KnittingEventType.knitAlongStart: return 'KnitAlong Start';
        case KnittingEventType.memo: return 'Memo';
      }
    }
  }

  String get emoji {
    switch (this) {
      case KnittingEventType.needlePurchase: return '🪡';
      case KnittingEventType.yarnPurchase: return '🧶';
      case KnittingEventType.patternPurchase: return '📄';
      case KnittingEventType.toolPurchase: return '🛒';
      case KnittingEventType.swatchComplete: return '✅';
      case KnittingEventType.projectStart: return '🚀';
      case KnittingEventType.projectComplete: return '🎉';
      case KnittingEventType.knitAlongStart: return '🤝';
      case KnittingEventType.memo: return '📝';
    }
  }

  bool get isPurchase => [
    KnittingEventType.needlePurchase,
    KnittingEventType.yarnPurchase,
    KnittingEventType.patternPurchase,
    KnittingEventType.toolPurchase,
  ].contains(this);
}

KnittingEventType knittingEventTypeFromValue(String value) {
  return KnittingEventType.values.firstWhere(
    (e) => e.value == value,
    orElse: () => KnittingEventType.memo,
  );
}

class KnittingEvent {
  final String id;
  final String userId;
  final KnittingEventType type;
  final String title;
  final String note;
  final DateTime date;
  final int amountWon;
  final String linkedProjectId;
  final bool isAutoGenerated;
  final DateTime createdAt;
  // #885 — 외부 캘린더 연동
  final String? gcalEventId;      // Google Calendar event ID
  final String? outlookEventId;   // Outlook event ID
  final DateTime? lastSyncedAt;   // 마지막 외부 캘린더 동기화 시각

  const KnittingEvent({
    required this.id,
    required this.userId,
    required this.type,
    required this.title,
    this.note = '',
    required this.date,
    this.amountWon = 0,
    this.linkedProjectId = '',
    this.isAutoGenerated = false,
    required this.createdAt,
    this.gcalEventId,
    this.outlookEventId,
    this.lastSyncedAt,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'userId': userId,
    'type': type.value,
    'title': title,
    'note': note,
    'date': Timestamp.fromDate(date),
    'amountWon': amountWon,
    'linkedProjectId': linkedProjectId,
    'isAutoGenerated': isAutoGenerated,
    'createdAt': Timestamp.fromDate(createdAt),
    if (gcalEventId != null) 'gcalEventId': gcalEventId,
    if (outlookEventId != null) 'outlookEventId': outlookEventId,
    if (lastSyncedAt != null) 'lastSyncedAt': Timestamp.fromDate(lastSyncedAt!),
  };

  factory KnittingEvent.fromJson(String id, Map<String, dynamic> json) {
    DateTime toDate(dynamic v) {
      if (v is Timestamp) return v.toDate();
      if (v is DateTime) return v;
      return DateTime.now();
    }
    return KnittingEvent(
      id: id,
      userId: json['userId'] as String? ?? '',
      type: knittingEventTypeFromValue(json['type'] as String? ?? 'memo'),
      title: json['title'] as String? ?? '',
      note: json['note'] as String? ?? '',
      date: toDate(json['date']),
      amountWon: (json['amountWon'] as num?)?.toInt() ?? 0,
      linkedProjectId: json['linkedProjectId'] as String? ?? '',
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      createdAt: toDate(json['createdAt']),
      gcalEventId: json['gcalEventId'] as String?,
      outlookEventId: json['outlookEventId'] as String?,
      lastSyncedAt: json['lastSyncedAt'] != null ? toDate(json['lastSyncedAt']) : null,
    );
  }

  KnittingEvent copyWith({
    String? title,
    String? note,
    DateTime? date,
    int? amountWon,
    String? linkedProjectId,
    String? gcalEventId,
    String? outlookEventId,
    DateTime? lastSyncedAt,
  }) => KnittingEvent(
    id: id,
    userId: userId,
    type: type,
    title: title ?? this.title,
    note: note ?? this.note,
    date: date ?? this.date,
    amountWon: amountWon ?? this.amountWon,
    linkedProjectId: linkedProjectId ?? this.linkedProjectId,
    isAutoGenerated: isAutoGenerated,
    createdAt: createdAt,
    gcalEventId: gcalEventId ?? this.gcalEventId,
    outlookEventId: outlookEventId ?? this.outlookEventId,
    lastSyncedAt: lastSyncedAt ?? this.lastSyncedAt,
  );
}
