import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

import '../../../providers/project_provider.dart';
import '../../../providers/blueprint_provider.dart';
import '../../../features/project/domain/project_model.dart';
import '../domain/knitting_event.dart';
import 'knitting_event_repository.dart';

String _v5(String name) =>
    const Uuid().v5(Namespace.url.value, name);

/// 수동 입력 이벤트 + 프로젝트/함뜨 자동 이벤트를 합산해 날짜별 맵으로 반환
final calendarEventsProvider =
    Provider.family<AsyncValue<Map<DateTime, List<KnittingEvent>>>, (int, int)>(
        (ref, ym) {
  final manualAsync = ref.watch(knittingEventsByMonthProvider(ym));
  final projectsAsync = ref.watch(projectListProvider);
  final kalsAsync = ref.watch(knitAlongGroupsProvider);

  if (manualAsync is AsyncLoading ||
      projectsAsync is AsyncLoading ||
      kalsAsync is AsyncLoading) {
    return const AsyncLoading();
  }

  final manual = manualAsync.valueOrNull ?? [];
  final projects = projectsAsync.valueOrNull ?? [];
  final kals = kalsAsync.valueOrNull ?? [];

  final year = ym.$1;
  final month = ym.$2;
  final monthStart = DateTime(year, month, 1);
  final monthEnd = DateTime(year, month + 1, 1);

  final autoEvents = <KnittingEvent>[];

  for (final p in projects) {
    if (p.startDate != null) {
      final d = DateTime(p.startDate!.year, p.startDate!.month, p.startDate!.day);
      if (!d.isBefore(monthStart) && d.isBefore(monthEnd)) {
        autoEvents.add(KnittingEvent(
          id: _v5('project-start-${p.id}'),
          userId: p.id,
          type: KnittingEventType.projectStart,
          title: p.title,
          date: d,
          linkedProjectId: p.id,
          isAutoGenerated: true,
          createdAt: p.startDate!,
        ));
      }
    }
    if (p.isFinished && p.finishDate != null) {
      final d = DateTime(p.finishDate!.year, p.finishDate!.month, p.finishDate!.day);
      if (!d.isBefore(monthStart) && d.isBefore(monthEnd)) {
        autoEvents.add(KnittingEvent(
          id: _v5('project-complete-${p.id}'),
          userId: p.id,
          type: KnittingEventType.projectComplete,
          title: p.title,
          date: d,
          linkedProjectId: p.id,
          isAutoGenerated: true,
          createdAt: p.finishDate!,
        ));
      }
    }
  }

  for (final kal in kals) {
    final d = DateTime(kal.createdAt.year, kal.createdAt.month, kal.createdAt.day);
    if (!d.isBefore(monthStart) && d.isBefore(monthEnd)) {
      autoEvents.add(KnittingEvent(
        id: _v5('kal-start-${kal.id}'),
        userId: kal.ownerUid,
        type: KnittingEventType.knitAlongStart,
        title: kal.title,
        date: d,
        isAutoGenerated: true,
        createdAt: kal.createdAt,
      ));
    }
  }

  final all = [...manual, ...autoEvents];
  final map = <DateTime, List<KnittingEvent>>{};
  for (final e in all) {
    final key = DateTime(e.date.year, e.date.month, e.date.day);
    map.putIfAbsent(key, () => []).add(e);
  }
  return AsyncData(map);
});
