import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../providers/auth_provider.dart';
import '../domain/knitting_event.dart';

class KnittingEventRepository {
  final FirebaseFirestore _db;
  final String _uid;

  KnittingEventRepository(this._db, this._uid);

  CollectionReference<Map<String, dynamic>> get _col =>
      _db.collection('users').doc(_uid).collection('knitting_events');

  Stream<List<KnittingEvent>> watchByMonth(int year, int month) {
    final start = DateTime(year, month, 1);
    final end = DateTime(year, month + 1, 1);
    return _col
        .where('date', isGreaterThanOrEqualTo: Timestamp.fromDate(start))
        .where('date', isLessThan: Timestamp.fromDate(end))
        .where('isAutoGenerated', isEqualTo: false)
        .orderBy('date')
        .snapshots()
        .map((s) => s.docs
            .map((d) => KnittingEvent.fromJson(d.id, d.data()))
            .toList());
  }

  Stream<List<KnittingEvent>> watchAll() {
    return _col
        .where('isAutoGenerated', isEqualTo: false)
        .orderBy('date', descending: true)
        .limit(200)
        .snapshots()
        .map((s) => s.docs
            .map((d) => KnittingEvent.fromJson(d.id, d.data()))
            .toList());
  }

  Future<void> save(KnittingEvent event) async {
    await _col.doc(event.id).set(event.toJson());
  }

  Future<void> delete(String id) async {
    await _col.doc(id).delete();
  }
}

final knittingEventRepositoryProvider =
    Provider<KnittingEventRepository>((ref) {
  final uid = ref.watch(authStateProvider).valueOrNull?.uid ?? '';
  return KnittingEventRepository(FirebaseFirestore.instance, uid);
});

final knittingEventsByMonthProvider =
    StreamProvider.family<List<KnittingEvent>, (int, int)>((ref, ym) {
  final repo = ref.watch(knittingEventRepositoryProvider);
  return repo.watchByMonth(ym.$1, ym.$2);
});
