// lib/features/blueprint/data/chart_to_units_converter.dart
//
// 이슈 #687 Phase B — 도안에디터 차트(grid+symbols) → 행별 1단=1 unit 자동 텍스트화.
// AI 호출 0 (좌표 기반 규칙 변환). PatternChart.toNarrative()의 RLE 결과를
// 행별로 분해해 StepBlueprintUnit으로 매핑한다.
//
// 사용 시점: pattern_repository._mirrorToBlueprint — aiSections가 없는 차트 도안 저장 시
// step_blueprints/{id}/units에 자동 단계 생성.
//
// 재변환 보존 정책: 자동 생성된 unit은 tags에 StepUnitTag(custom, 'auto:chart') 부여 →
// 사용자 직접 편집한 unit과 구분 가능 (isAutoGenerated 헬퍼).

import '../../../core/domain/step_unit/step_unit_tag.dart';
import '../../pattern/domain/pattern_chart.dart';
import '../domain/step_blueprint_unit.dart';

class ChartToUnitsConverter {
  /// 차트 행별로 unit 생성. order = row index, title = "${i+1}단", instruction = RLE 라인.
  ///
  /// [korean]: true면 한국어 라벨/지시문, false면 영문.
  static List<StepBlueprintUnit> convert({
    required PatternChart chart,
    required String blueprintId,
    bool korean = true,
  }) {
    // PatternChart.toNarrative() — 이미 존재(L443-494). RLE 결과를 행 단위로 반환.
    final narrative = chart.toNarrative(korean: korean);
    final lines = narrative
        .split('\n')
        .where((l) => l.trim().isNotEmpty)
        .toList();
    final now = DateTime.now();
    final units = <StepBlueprintUnit>[];

    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      final colonIdx = line.indexOf(':');
      final title = colonIdx >= 0
          ? line.substring(0, colonIdx).trim()
          : (korean ? '${i + 1}단' : 'Row ${i + 1}');
      final instruction =
          colonIdx >= 0 ? line.substring(colonIdx + 1).trim() : line.trim();

      units.add(StepBlueprintUnit(
        id: '${blueprintId}_r${i + 1}',
        blueprintId: blueprintId,
        order: i,
        title: title,
        titleKo: korean ? title : null,
        titleEn: korean ? null : title,
        instruction: instruction,
        instructionKo: korean ? instruction : null,
        instructionEn: korean ? null : instruction,
        targetRows: 1,
        referenceImages: const [],
        chartRegion: ChartRegion(
          rowStart: i,
          rowEnd: i,
          colStart: 0,
          colEnd: chart.cols - 1,
        ),
        isPreview: false,
        tags: const [StepUnitTag(StepUnitTagKind.custom, 'auto:chart')],
        createdAt: now,
      ));
    }
    return units;
  }

  /// 서술형 도안(narrativeText) 행별 분해 → unit.
  /// ChartMode.narrative이거나 grid가 비었지만 narrativeText만 있는 경우 사용.
  static List<StepBlueprintUnit> convertFromNarrativeText({
    required String narrativeText,
    required String blueprintId,
    bool korean = true,
  }) {
    final lines = narrativeText
        .split('\n')
        .where((l) => l.trim().isNotEmpty)
        .toList();
    final now = DateTime.now();
    final units = <StepBlueprintUnit>[];

    for (var i = 0; i < lines.length; i++) {
      final line = lines[i].trim();
      final colonIdx = line.indexOf(':');
      final title = colonIdx >= 0
          ? line.substring(0, colonIdx).trim()
          : (korean ? '${i + 1}단' : 'Row ${i + 1}');
      final instruction =
          colonIdx >= 0 ? line.substring(colonIdx + 1).trim() : line;

      units.add(StepBlueprintUnit(
        id: '${blueprintId}_n${i + 1}',
        blueprintId: blueprintId,
        order: i,
        title: title,
        titleKo: korean ? title : null,
        titleEn: korean ? null : title,
        instruction: instruction,
        instructionKo: korean ? instruction : null,
        instructionEn: korean ? null : instruction,
        targetRows: 1,
        referenceImages: const [],
        isPreview: false,
        tags: const [StepUnitTag(StepUnitTagKind.custom, 'auto:narrative')],
        createdAt: now,
      ));
    }
    return units;
  }

  /// 변경 감지 — 기존 units가 자동 생성된 것인지 확인.
  /// 재변환 시 사용자 편집 보존하려면 호출부에서 이 헬퍼로 분기.
  static bool isAutoGenerated(StepBlueprintUnit unit) {
    return unit.tags.any((t) =>
        t.kind == StepUnitTagKind.custom &&
        (t.value == 'auto:chart' || t.value == 'auto:narrative'));
  }
}
