// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9O6zO3XHRCKM7vIvPbUrSjhvjGiibm44',
    appId: '1:683285854424:android:b491ac049c66f0b821bfad',
    messagingSenderId: '683285854424',
    projectId: 'moriknit-ceea9',
    storageBucket: 'moriknit-ceea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVD2U-12B251kdYJd9jqgsL5EX2pQe4U',
    appId: '1:683285854424:ios:4a3a398aa9f2758a21bfad',
    messagingSenderId: '683285854424',
    projectId: 'moriknit-ceea9',
    storageBucket: 'moriknit-ceea9.firebasestorage.app',
    iosClientId: '683285854424-pt9koaoptj7inqdp1u37c1nuscnp7dae.apps.googleusercontent.com',
    iosBundleId: 'com.moriknit.moriknitFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArA0OO9Wd1edo2BW9Enpe-AMhm8eUN3c0',
    appId: '1:683285854424:web:31cebe736d620b4d21bfad',
    messagingSenderId: '683285854424',
    projectId: 'moriknit-ceea9',
    authDomain: 'moriknit-ceea9.firebaseapp.com',
    storageBucket: 'moriknit-ceea9.firebasestorage.app',
  );

}